-- local f = string.format
--
-- function describe(name, fn, ...)
-- 	print("running test " .. name)
-- 	for _, case in ipairs(...) do
-- 		local ok, result = pcall(fn, case.input)
-- 		if not ok or result ~= case.expected then
-- 			print(
-- 				"  case " .. case.name .. " failed: expected " .. f("%s", case.expected) .. ", got " .. f("%s", result)
-- 			)
-- 		end
-- 	end
-- end
--
-- function case(input, expected)
-- 	return { input = input, expected = expected }
-- end
