require("willothy.keymap.normal")
require("willothy.keymap.window")
require("willothy.keymap.editor")
require("willothy.keymap.terminal")
require("willothy.keymap.cycle")
require("willothy.keymap.view")
require("willothy.keymap.git")
