-- local NC = require("nui-components")
--
-- local Buffer = require("nui-components.buffer")
-- local view = NC.create_renderer({
--   width = math.floor(vim.o.columns / 2),
--   height = math.floor(vim.o.lines / 2),
-- })
--
-- local Terminal = require("toggleterm.terminal").Terminal:new({
--   cmd = "btm",
-- })
--
-- Terminal:spawn()
--
-- view:render(function()
--   return NC.rows(
--     {
--       flex = 1,
--     },
--     Buffer({
--       buf = Terminal.bufnr,
--       autofocus = true,
--       flex = 1,
--     }, {
--       win_options = {
--         signcolumn = "no",
--         statuscolumn = " ",
--       },
--     })
--   )
-- end)
